title: Operate First Community Handbook
author: Operate First Authors
logo: img/icon.png
execute:
  execute_notebooks: 'off'
repository:
  url: https://github.com/operate-first/community-handbook
  path_to_book: .
  branch: main

# See https://jupyterbook.org/customize/config.html#add-a-link-to-your-repository
html:
  favicon: img/favicon.png
  use_issues_button: true
  use_repository_button: true
